[package]
name = "oxidized"
version = "0.1.0"
authors = ["PintaPontus <matteo.blascoviz@gmail.com>"]
description = "Rust Hello World"
repository = "https://github.com/PintaPontus/Oxidized"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
